# Generated by Django 5.1.1 on 2024-11-11 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busketName', models.CharField(max_length=20)),
                ('busketPrice', models.CharField(max_length=20)),
                ('busketShop', models.CharField(max_length=20)),
                ('busketShopUrl', models.CharField(max_length=20)),
                ('busketCategory', models.CharField(max_length=20)),
                ('userImage', models.ImageField(blank=True, default='default.jpeg', upload_to='buscketImage/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
